from ozz_backend.database.entity.material_bridge_tb import MaterialBridgeTB
from ozz_backend.database.entity.material_tb import MaterialTB
from ozz_backend.database.entity.mission_tb import MissionTB
from ozz_backend.database.entity.ozz_cd_tb import OzzCdTB
from ozz_backend.database.entity.quest_tb import QuestTB
from ozz_backend.database.entity.quest_bridge_tb import QuestBridgeTB
from ozz_backend.database.entity.user_proto_tb import UserProtoTB
from ozz_backend.database.entity.user_ongoing_proto_tb import UserOngoingProtoTB
from ozz_backend.database.entity.user_mission_log_tb import UserMissionLogTB
from ozz_backend.database.entity.user_quest_log_tb import UserQuestLogTB
